/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReservacionesUI;

import java.sql.Statement;
import conexion.ConexionBD;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Melanie Guzmán
 */
public class InterfazCocina extends javax.swing.JFrame {
    String [] datos = new String[4];
    String [] datos1 = new String[100];
    ConexionBD conn = new ConexionBD();
    Connection ConexionBD = conn.getConnection();
    PreparedStatement st;
    /**
     * Creates new form InterfazCocina
     */
    public InterfazCocina() {
        initComponents();
        mostrar();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numero Orden");
        model.addColumn("Comanda");
        model.addColumn("Platillo");
        model.addColumn("Cantidad");
        TablaProceso.setModel(model);
        

    }
    
    public void mostrar(){
        String sql = "select idComanda, idPlatillo, cantidad FROM platillosporcomanda order by idComanda asc";
        Statement st;

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Comanda");
        model.addColumn("Platillo");
        model.addColumn("Cantidad");
        TablaEntrada.setModel(model);
        
        try{
            st=ConexionBD.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while(rs.next()){
                datos[0]=rs.getString(1);                
                
                datos[1]=rs.getString(2);
                int opc = Integer.parseInt(datos[1]);
                    switch(opc){
                    case 1 -> datos[1]="Ramen";
                    case 2 -> datos[1]="Curry Japonés";
                    case 3 -> datos[1]="Sushi de carne y bacon";
                    case 4 -> datos[1]="Salmón marinado japonés";
                    case 6 -> datos[1]="Mochis de Coco";
                    case 7 -> datos[1]="Bubble Waffle";
                }
                datos[2]=rs.getString(3);

                model.addRow(datos);

                
        }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error"+ e.toString());
            }
                        int j = Integer.parseInt(datos[0]);
        for(int i=1;i<=j;i++){
            CBPlatillo.addItem(String.valueOf(i));
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnOrden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEntrada = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProceso = new javax.swing.JTable();
        CBPlatillo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MenuCocina = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        IngreMenu = new javax.swing.JMenu();
        InterIngre = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitar Orden");

        jPanel1.setBackground(new java.awt.Color(32, 17, 162));

        jLabel1.setForeground(new java.awt.Color(85, 231, 255));
        jLabel1.setText(">>>");

        BtnOrden.setText("Completar Pedido");
        BtnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrdenActionPerformed(evt);
            }
        });

        TablaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEntrada);

        TablaProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaProceso);

        CBPlatillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Orden" }));
        CBPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPlatilloActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(85, 231, 255));
        jLabel2.setText("Orden en Proceso:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 231, 255));
        jLabel3.setText("Orden Completada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOrden)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1))
                    .addComponent(CBPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnOrden)
                        .addGap(49, 49, 49))
                    .addComponent(CBPlatillo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Control");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Control Ingredientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        MenuCocina.add(jMenu1);

        IngreMenu.setText("Recetas");

        InterIngre.setText("Platillos");
        InterIngre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterIngreActionPerformed(evt);
            }
        });
        IngreMenu.add(InterIngre);

        jMenuItem1.setText("Postres");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        IngreMenu.add(jMenuItem1);

        MenuCocina.add(IngreMenu);

        setJMenuBar(MenuCocina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrdenActionPerformed
        // TODO add your handling code here:
      

        int opcion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de realizar esta operación?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            String comanda;
        comanda=CBPlatillo.getSelectedItem().toString();
        int comanda1 = Integer.parseInt(comanda);
        
        String sql = "SELECT idComanda, idPlatillo, cantidad FROM platillosporcomanda WHERE idComanda=?";
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numero Orden");
        model.addColumn("Comanda");
        model.addColumn("Platillo");
        model.addColumn("Cantidad");
        TablaProceso.setModel(model);
        try{
            st = ConexionBD.prepareStatement(sql);
            st.setInt(1,comanda1);
            System.out.println(st);
            ResultSet rs = st.executeQuery();
            
            while(rs.next()){
                //comanda1 = rs.getInt("idComanda");
                datos[0]=rs.getString(1);                
                
                datos[1]=rs.getString(2);
                int opc = Integer.parseInt(datos[1]);
                    switch(opc){
                    case 1 -> datos[1]="Ramen";
                    case 2 -> datos[1]="Curry Japonés";
                    case 3 -> datos[1]="Sushi de carne y bacon";
                    case 4 -> datos[1]="Salmón marinado japonés";
                    case 6 -> datos[1]="Mochis de Coco";
                    case 7 -> datos[1]="Bubble Waffle";
                }
                datos[2]=rs.getString(3);

                model.addRow(datos);
                    
                
        }
            } catch(SQLException e){
                JOptionPane.showMessageDialog(null,"Error"+ e.toString());
            }
        String sql1 = "UPDATE mesa set estado = 6 where idMesa = (select idMesa from reservacion where FolioReserva = (select FolioReserva from comanda where idComanda=?))";
        try{
            st = ConexionBD.prepareStatement(sql1);
            st.setInt(1,comanda1);
            System.out.println(st);
            st.executeUpdate();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error"+ e.toString());
        }

        
            // Realizar la operación aquí
        } else {
            // Cancelar la operación o realizar acciones alternativas aquí
        }
    }//GEN-LAST:event_BtnOrdenActionPerformed

    private void InterIngreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterIngreActionPerformed
        InterfazPlatillos abrir = new InterfazPlatillos();
        abrir.setVisible(true);
    }//GEN-LAST:event_InterIngreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        InterfazPostres abrir = new InterfazPostres();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        InterfazControl_Ingr abrir = new InterfazControl_Ingr();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void CBPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPlatilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPlatilloActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCocina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCocina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOrden;
    private javax.swing.JComboBox<String> CBPlatillo;
    private javax.swing.JMenu IngreMenu;
    private javax.swing.JMenuItem InterIngre;
    private javax.swing.JMenuBar MenuCocina;
    private javax.swing.JTable TablaEntrada;
    private javax.swing.JTable TablaProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
