/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ReservacionesUI;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Melanie Guzmán
 */
public class InterfazPlatillos extends javax.swing.JFrame {
        DefaultListModel modelo = new DefaultListModel();
    /**
     * Creates new form InterfazIngredientes
     */
    public InterfazPlatillos() {
        initComponents();
        ListaPlatillos.setModel(modelo);
        
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CBPlatillos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPlatillos = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Platillos");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        CBPlatillos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platillos", "Ramen", "Curry japonés", "Sushi de carne y bacon", "Salmón marinado jápones", " " }));
        CBPlatillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPlatillosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaPlatillos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(CBPlatillos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CBPlatillos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu1.setText("Control");

        jMenuItem1.setText("Cocina");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Control Ingredientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBPlatillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPlatillosActionPerformed
        modelo.removeAllElements();
        String platillo;
        platillo=CBPlatillos.getSelectedItem().toString();

        if(platillo=="Ramen"){
            modelo.addElement("•220 gramos de zanahoria");
            modelo.addElement("•220 gramos de cebolleta");
            modelo.addElement("•200 gramos de espinacas");
            modelo.addElement("•200 gramos de setas o champiñones");
            modelo.addElement("•200 gramos de tofu");
            modelo.addElement("•100 gramos de fideos de arroz");
            modelo.addElement("•2 ajos");
            modelo.addElement("•1 cucharadita de jengibre en polvo");
            modelo.addElement("•1 cucharada sopera de miso o un sobre de miso");
            modelo.addElement("•1 litro de caldo de verduras");
            modelo.addElement("•1 cucharadita de sal");
            modelo.addElement("•1 cucharadita de vinagre de arroz");
            modelo.addElement("•1 cucharadita de salsa de soja dulce");
      
        } else if (platillo=="Curry japonés"){            
            modelo.addElement("•600 gramos de pechuga de pollo");
            modelo.addElement("•1 litro de agua");
            modelo.addElement("•500 mililitros de caldo de pollo");
            modelo.addElement("•1 cebolla");
            modelo.addElement("•2 zanahorias");
            modelo.addElement("•100 gramos de judías verdes o edamame");
            modelo.addElement("•150 gramos de setas shitake o champiñones");
            modelo.addElement("•1 chorro de aceite de girasol");
            modelo.addElement("•1 pizca de sal");
            modelo.addElement("•1 pizca de pimienta");
            modelo.addElement("•4 cucharadas soperas de mantequilla");
            modelo.addElement("•2 cucharadas soperas de harina");
            modelo.addElement("•2 cucharadas soperas de garam masala o harissa o 1 pastilla de curry japonés");   
            }
            else if (platillo=="Sushi de carne y bacon"){
            modelo.addElement("•½ taza de Arroz para sushi");
            modelo.addElement("•1 taza de Agua (240 mililitros)");
            modelo.addElement("•60 mililitros de Vinagre de arroz"); 
            modelo.addElement("•1 cucharada sopera de Azúcar");
            modelo.addElement("•2 cucharadas de postre de Sal");
            modelo.addElement("•2 láminas de Alga nori");
            modelo.addElement("•2 unidades de Filetes de ternera");
            modelo.addElement("•2 lonchas de Bacon");


    } else if (platillo=="Salmón marinado jápones"){
            modelo.addElement("•400 gramos de Salmón fresco");
            modelo.addElement("•1 pizca de Jengibre en polvo");
            modelo.addElement("•1 pizca de Pasta de ajo"); 
            modelo.addElement("•1 cucharadita de Azúcar");
            modelo.addElement("•100 mililitros de Salsa de soja");
            modelo.addElement("•100 mililitros de Vinagre de arroz");
            modelo.addElement("•100 gramos de Cebolla larga o de verdeo");
            modelo.addElement("•2 cucharaditas de Ajonjolí");
            modelo.addElement("•1 pizca de sal");
            modelo.addElement("•1 pizca de pimienta negra");
            modelo.addElement("•1 cucharadita de Sake");
    }
            

            /*for(int i=0;i<array.size();i++){
                modelo.addElement(array.get(i));
            }
            */
    }//GEN-LAST:event_CBPlatillosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        InterfazCocina abrir = new InterfazCocina();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        InterfazControl_Ingr abrir = new InterfazControl_Ingr();
        abrir.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
          
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPlatillos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPlatillos().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBPlatillos;
    private javax.swing.JList<String> ListaPlatillos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
