package ReservacionesUI;

/**
 * Clase que representa el menú principal de la aplicación de reservaciones en Neo Tokio.
 * Permite acceder a las sucursales disponibles y al registro de clientes.
 * 
 * @author Pedro Quiroz
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Constructor que inicializa los componentes del formulario.
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelIconSushiRoll = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSucursalAllende = new javax.swing.JButton();
        jButtonSucursalGalerias = new javax.swing.JButton();
        jButtonSucursalEspacio = new javax.swing.JButton();
        jButtonSucursalExpoPlaza = new javax.swing.JButton();
        jButtonSucursalAvUniversidad = new javax.swing.JButton();
        jButtonSucursalVillaAsuncion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonAbrirRegistroCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 17, 72));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 253), 3, true));

        jLabel1.setFont(new java.awt.Font("Barlow Condensed Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 253));
        jLabel1.setText("Bienvenido al Sistema de Reservaciones NEO TOKIO");

        jLabelIconSushiRoll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Logo Neo Tokio SushiRoll.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Barlow Condensed Light", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 253));
        jLabel2.setText("Sucursales Disponibles ");

        jButtonSucursalAllende.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalAllende.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 48)); // NOI18N
        jButtonSucursalAllende.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalAllende.setText("Allende");
        jButtonSucursalAllende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSucursalAllendeActionPerformed(evt);
            }
        });

        jButtonSucursalGalerias.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalGalerias.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 48)); // NOI18N
        jButtonSucursalGalerias.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalGalerias.setText("Galerias");

        jButtonSucursalEspacio.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalEspacio.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 48)); // NOI18N
        jButtonSucursalEspacio.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalEspacio.setText("Espacio");

        jButtonSucursalExpoPlaza.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalExpoPlaza.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 48)); // NOI18N
        jButtonSucursalExpoPlaza.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalExpoPlaza.setText("Expo Plaza");

        jButtonSucursalAvUniversidad.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalAvUniversidad.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 36)); // NOI18N
        jButtonSucursalAvUniversidad.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalAvUniversidad.setText("Av. Universidad");

        jButtonSucursalVillaAsuncion.setBackground(new java.awt.Color(85, 231, 255));
        jButtonSucursalVillaAsuncion.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 36)); // NOI18N
        jButtonSucursalVillaAsuncion.setForeground(new java.awt.Color(32, 17, 72));
        jButtonSucursalVillaAsuncion.setText("Villa Asuncion");

        jLabel3.setFont(new java.awt.Font("Barlow Condensed Light", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 253));
        jLabel3.setText("Todavia no estas registrado en nuestro sistema?. Registrate ahora para poder reservar mesas y obtener premios con cada compra!");

        jButtonAbrirRegistroCliente.setFont(new java.awt.Font("Barlow Condensed Medium", 0, 24)); // NOI18N
        jButtonAbrirRegistroCliente.setText("¡Registrame!");
        jButtonAbrirRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirRegistroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAbrirRegistroCliente)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelIconSushiRoll)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(251, 251, 251)
                                    .addComponent(jLabel2))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonSucursalExpoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSucursalAllende, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonSucursalGalerias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSucursalEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonSucursalAvUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonSucursalVillaAsuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconSushiRoll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSucursalAllende, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSucursalGalerias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSucursalEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSucursalExpoPlaza, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSucursalAvUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSucursalVillaAsuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAbrirRegistroCliente)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSucursalAllendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSucursalAllendeActionPerformed
        // TODO add your handling code here:
        // Acción al hacer clic en el botón de la sucursal Allende, se mostrara la ventana de la sucursal Allende.
        Sucursal_Allende sucursalAllende = new Sucursal_Allende();
        sucursalAllende.setVisible(true);
    }//GEN-LAST:event_jButtonSucursalAllendeActionPerformed

    private void jButtonAbrirRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirRegistroClienteActionPerformed
        // TODO add your handling code here:
        // Acción al hacer clic en el botón para abrir el registro de cliente.
        // Crear una instancia de RegistroCliente
        RegistroCliente registroCliente = new RegistroCliente();

        // Hacer visible la nueva ventana
        registroCliente.setVisible(true);
    }//GEN-LAST:event_jButtonAbrirRegistroClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirRegistroCliente;
    private javax.swing.JButton jButtonSucursalAllende;
    private javax.swing.JButton jButtonSucursalAvUniversidad;
    private javax.swing.JButton jButtonSucursalEspacio;
    private javax.swing.JButton jButtonSucursalExpoPlaza;
    private javax.swing.JButton jButtonSucursalGalerias;
    private javax.swing.JButton jButtonSucursalVillaAsuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIconSushiRoll;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
