package ReservacionesUI;

import conexion.ConexionBD;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Quiroz
 */
public class Sucursal extends javax.swing.JFrame {

    /**
     * Creates new form Sucursal
     */
    public Sucursal() {
        initComponents();
        loadRestaurantes();
        addListSelectionListener();
    }

    private void loadRestaurantes() {
        List<String> restaurantes = new ArrayList<>();

        try ( Connection connection = ConexionBD.getConnection()) {
            String sql = "SELECT nombre FROM sucursal";
            try ( PreparedStatement statement = connection.prepareStatement(sql)) {
                try ( ResultSet resultSet = statement.executeQuery()) {
                    while (resultSet.next()) {
                        String nombre = resultSet.getString("nombre");
                        restaurantes.add(nombre);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        // Populate the JList
        lstRestaurantes.setListData(restaurantes.toArray(new String[0]));
    }

    private void addListSelectionListener() {
        lstRestaurantes.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Get the selected restaurant's idSucursal
                    int selectedIndex = lstRestaurantes.getSelectedIndex();
                    if (selectedIndex != -1) {
                        String selectedRestaurant = lstRestaurantes.getSelectedValue();
                        int idSucursal = getIdSucursal(selectedRestaurant);

                        // Pass idSucursal to MesaReservacion
                        openMesaReservacion(idSucursal);
                    }
                }
            }
        });
    }

    private int getIdSucursal(String nombreRestaurante) {
        int idSucursal = -1;

        try ( Connection connection = ConexionBD.getConnection()) {
            String sql = "SELECT idSucursal FROM sucursal WHERE nombre = ?";
            try ( PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, nombreRestaurante);
                try ( ResultSet resultSet = statement.executeQuery()) {
                    if (resultSet.next()) {
                        idSucursal = resultSet.getInt("idSucursal");
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        return idSucursal;
    }

    private void openMesaReservacion(int idSucursal) {
        int response = JOptionPane.showConfirmDialog
        (this, "Acceder a Sucursal " + idSucursal + "?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            MesaReservacion mesaReservacion = new MesaReservacion(idSucursal);
            mesaReservacion.setVisible(true);
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNeoTokyo = new javax.swing.JLabel();
        lblRestaurantes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRestaurantes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNeoTokyo.setBackground(new java.awt.Color(255, 0, 153));
        lblNeoTokyo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        lblNeoTokyo.setForeground(new java.awt.Color(255, 0, 153));
        lblNeoTokyo.setText("Neo Tokyo");

        lblRestaurantes.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRestaurantes.setText("Sucursales");

        lstRestaurantes.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(lstRestaurantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNeoTokyo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRestaurantes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNeoTokyo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRestaurantes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNeoTokyo;
    private javax.swing.JLabel lblRestaurantes;
    private javax.swing.JList<String> lstRestaurantes;
    // End of variables declaration//GEN-END:variables
}
